language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"


# install dependencies
install:
  #- pip install -r requirements.txt
  - pip install .
  #install blast
  - wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-x64-linux.tar.gz -O /tmp/blast.tar.gz
  - tar -xvzf /tmp/blast.tar.gz
  - export PATH=$PATH:$PWD/ncbi-blast-2.10.0+/bin/

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

# command to run tests
script:
  - ls
  #- travis_wait 40 coverage run -m pytest tests/
  - bash tests/test.sh
